apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: websphere-liberty

resources:
  - websphere-liberty-crd.yaml
  - websphere-liberty-deployment.yaml
  - websphere-liberty-roles.yaml
