apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wlo-watched-ns2

bases:
- ../../../overlays/watch-another-namespace/wlo-watched-ns

patchesStrategicMerge:
- watched-roles.yaml
