apiVersion: v1
kind: ServiceAccount
metadata:
  name: websphere-liberty-controller-manager
  labels:
    app.kubernetes.io/instance: websphere-liberty-operator
    app.kubernetes.io/name: websphere-liberty-operator
