apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: websphere-liberty-operator
    app.kubernetes.io/name: websphere-liberty-operator
    control-plane: websphere-liberty-controller-manager
  name: websphere-liberty-controller-manager
  namespace: websphere-liberty
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: websphere-liberty-operator
      app.kubernetes.io/name: websphere-liberty-operator
      control-plane: websphere-liberty-controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        productChargedContainers: ALL
        productID: cb1747ecb831410f88006195f024183f
        productMetric: FREE
        productName: WebSphere Liberty Operator
      labels:
        app.kubernetes.io/instance: websphere-liberty-operator
        app.kubernetes.io/name: websphere-liberty-operator
        control-plane: websphere-liberty-controller-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_LIBERTY_SAMPLE_APP
          value: icr.io/appcafe/open-liberty/samples/getting-started@sha256:d3c67c4a15c97b0fb82f9ef4a2ccf474232b878787e9eea39af75a3ac78469e3
        - name: RELATED_IMAGE_WEBSPHERE_LIBERTY_OPERATOR
          value: cp.stg.icr.io/cp/websphere-liberty-operator:main
        image: cp.stg.icr.io/cp/websphere-liberty-operator:main
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: manager
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: websphere-liberty-controller-manager
      terminationGracePeriodSeconds: 10
