apiVersion: apps/v1
kind: Deployment
metadata:
  name: websphere-liberty-controller-manager
  labels:
    control-plane: websphere-liberty-controller-manager
    app.kubernetes.io/instance: websphere-liberty-operator
    app.kubernetes.io/name: websphere-liberty-operator
spec:
  selector:
    matchLabels:
      control-plane: websphere-liberty-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: websphere-liberty-controller-manager
      annotations:
        productID: "cb1747ecb831410f88006195f024183f"
        productName: "WebSphere Liberty Operator"
        productMetric: "FREE"
        productChargedContainers: "ALL"
    spec:
      hostIPC: false
      hostPID: false
      hostNetwork: false
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - "--health-probe-bind-address=:8081"
        - "--metrics-bind-address=127.0.0.1:8080"
        - --enable-leader-election
        image: cp.stg.icr.io/cp/websphere-liberty-operator@sha256:63d779b803ae8d69244da9498d4e27c4d92154159cc51125fbbcbcc7c4e5acad
        name: manager
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 128Mi
      serviceAccountName: websphere-liberty-controller-manager
      terminationGracePeriodSeconds: 10
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
