apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: websphere-liberty-operator
    app.kubernetes.io/name: websphere-liberty-operator
  name: websphere-liberty-controller-manager
  namespace: websphere-liberty
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: websphere-liberty-operator
    app.kubernetes.io/name: websphere-liberty-operator
  name: websphere-liberty-leader-election-role
  namespace: websphere-liberty
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: websphere-liberty-operator
    app.kubernetes.io/name: websphere-liberty-operator
  name: websphere-liberty-manager-role
  namespace: websphere-liberty
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  - statefulsets
  verbs:
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  - imagestreamtags
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - liberty.websphere.ibm.com
  resources:
  - webspherelibertyapplications
  - webspherelibertyapplications/finalizers
  - webspherelibertyapplications/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - liberty.websphere.ibm.com
  resources:
  - webspherelibertydumps
  - webspherelibertydumps/finalizers
  - webspherelibertydumps/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - liberty.websphere.ibm.com
  resources:
  - webspherelibertytraces
  - webspherelibertytraces/finalizers
  - webspherelibertytraces/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - restricted
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: websphere-liberty-operator
    app.kubernetes.io/name: websphere-liberty-operator
  name: websphere-liberty-leader-election-rolebinding
  namespace: websphere-liberty
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: websphere-liberty-leader-election-role
subjects:
- kind: ServiceAccount
  name: websphere-liberty-controller-manager
  namespace: websphere-liberty
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: websphere-liberty-operator
    app.kubernetes.io/name: websphere-liberty-operator
  name: websphere-liberty-manager-rolebinding
  namespace: websphere-liberty
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: websphere-liberty-manager-role
subjects:
- kind: ServiceAccount
  name: websphere-liberty-controller-manager
  namespace: websphere-liberty
