apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: websphere-liberty-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: websphere-liberty-operator
    config.openshift.io/inject-trusted-cabundle: "true"
  name: wlo-trusted-ca
