apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: websphere-liberty-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: websphere-liberty-operator
  name: wlo-controller-manager
