apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wlo-ns


resources:
- ../../../base
patches:
- path: wlo-deployment.yaml
- path: websphere-liberty-leader-election-role.yaml
- path: websphere-liberty-manager-role.yaml
- path: websphere-liberty-leader-election-rolebinding.yaml
- path: websphere-liberty-manager-rolebinding.yaml
- path: wlo-sa.yaml
