apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wlo-ns


resources:
- ../../../base
patches:
- path: wlo-deployment.yaml
- path: roles-patch1.yaml
- path: roles-patch2.yaml
- path: roles-patch3.yaml
- path: roles-patch4.yaml
- path: wlo-sa.yaml
