$patch: delete
apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace:
    $patch: delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace:
    $patch: delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
  namespace:
    $patch: delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
  namespace:
    $patch: delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  namespace:
    $patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace:
    $patch: delete
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            $patch: delete
          value: WEBSPHERE_LIBERTY_WATCH_NAMESPACE
