apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            $patch: delete
          value: WEBSPHERE_LIBERTY_WATCH_NAMESPACE
          
