apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../rbac
- ../../manager

namePrefix: wlo-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/instance: websphere-liberty-operator
  app.kubernetes.io/managed-by: olm
  app.kubernetes.io/name: websphere-liberty-operator

patches:
- path: patches/delete-namespace.yaml
  target:
    kind: Namespace

patchesJson6902:
  - target:
      namespace: system
      name: .*
    patch: |-
      - op: remove
        path: /metadata/namespace
  - target:
      namespace: websphere-liberty-operator
      name: .*
    patch: |-
      - op: remove
        path: /metadata/namespace
  - target:
      kind: RoleBinding
      name: .*
    patch: |-
      - op: remove
        path: /subjects/0/namespace
  - target:
      kind: Deployment
      name: wlo-controller-manager
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env/1/valueFrom
      - op: add
        path: /spec/template/spec/containers/0/env/1/value
        value: WEBSPHERE_LIBERTY_WATCH_NAMESPACE