apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wlo-watched-ns2


resources:
- ../../../overlays/watch-another-namespace/wlo-watched-ns
patches:
- path: wlo-watched-role.yaml
- path: wlo-watched-rolebinding.yaml
- path: wlo-leader-election-watched-role.yaml
- path: wlo-leader-election-watched-rolebinding.yaml
