apiVersion: v1
kind: ServiceAccount
metadata:
  name: scorecard-kuttl-watch-all
  namespace: WEBSPHERE_LIBERTY_WATCH_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scorecard-kuttl-watch-all
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scorecard-kuttl-watch-all
subjects:
- kind: ServiceAccount
  name: scorecard-kuttl-watch-all
  namespace: WEBSPHERE_LIBERTY_WATCH_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scorecard-kuttl-watch-all
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - routes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - liberty.websphere.ibm.com
  resources:
  - webspherelibertyapplications
  - webspherelibertydumps
  - webspherelibertytraces
  verbs:
  - get
  - list
  - create
  - patch
  - delete
