apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Auto Pilot
    categories: Application Runtime
    certified: "true"
    createdAt: "2021-11-25T14:00:00Z"
    description: Deploy and manage applications running on Liberty
    repository: https://github.com/WASdev/websphere-liberty-operator
    support: IBM
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/os.linux: supported
  name: ibm-websphere-liberty.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Represents the deployment of an WebSphere Liberty application
      displayName: WebSphereLibertyApplication
      kind: WebSphereLibertyApplication
      name: webspherelibertyapplications.liberty.websphere.ibm.com
      resources:
      - kind: Deployment
        name: ""
        version: v1
      - kind: HorizontalPodAutoscaler
        name: ""
        version: v1
      - kind: Route
        name: ""
        version: v1
      - kind: Secret
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      - kind: ServiceAccount
        name: ""
        version: v1
      - kind: StatefulSet
        name: ""
        version: v1
      specDescriptors:
      - description: Application image to deploy.
        displayName: Application Image
        path: applicationImage
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Required field for autoscaling. Upper limit for the number of pods that can be set by the autoscaler. Parameter .spec.resources.requests.cpu must also be specified.
        displayName: Max Replicas
        path: autoscaling.maxReplicas
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: Name of the application. Defaults to the name of this custom resource.
        displayName: Application Name
        path: applicationName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Lower limit for the number of pods that can be set by the autoscaler.
        displayName: Min Replicas
        path: autoscaling.minReplicas
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: Version of the application.
        displayName: Application Version
        path: applicationVersion
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Target average CPU utilization, represented as a percentage of requested CPU, over all the pods.
        displayName: Target CPU Utilization Percentage
        path: autoscaling.targetCPUUtilizationPercentage
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: Policy for pulling container images. Defaults to IfNotPresent.
        displayName: Pull Policy
        path: pullPolicy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:imagePullPolicy
      - description: Name of the Secret to use to pull images from the specified repository. It is not required if the cluster is configured with a global image pull secret.
        displayName: Pull Secret
        path: pullSecret
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
      - description: Name of the service account to use for deploying the application. A service account is automatically created if it's not specified.
        displayName: Service Account Name
        path: serviceAccountName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Create Knative resources and use Knative serving.
        displayName: Create Knative Service
        path: createKnativeService
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Expose the application externally via a Route, a Knative Route or an Ingress resource.
        displayName: Expose
        path: expose
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Number of pods to create. Not applicable when .spec.autoscaling or .spec.createKnativeService is specified.
        displayName: Replicas
        path: replicas
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podCount
      - description: The port exposed by the container.
        displayName: Service Port
        path: service.port
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - displayName: Auto Scaling
        path: autoscaling
      - displayName: Service Type
        path: service.type
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Resource requests and limits for the application container.
        displayName: Resource Requirements
        path: resources
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:resourceRequirements
      - description: Node proxies this port into your service.
        displayName: Node Port
        path: service.nodePort
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - displayName: Probes
        path: probes
      - description: The name for the port exposed by the container.
        displayName: Port Name
        path: service.portName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Deployment
        path: deployment
      - description: Annotations to be added to the service.
        displayName: Service Annotations
        path: service.annotations
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: The port that the operator assigns to containers inside pods. Defaults to the value of .spec.service.port.
        displayName: Target Port
        path: service.targetPort
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - displayName: StatefulSet
        path: statefulSet
      - displayName: Service
        path: service
      - description: 'A name of a secret that already contains TLS key, certificate and CA to be mounted in the pod. The following keys are valid in the secret: ca.crt, tls.crt, and tls.key.'
        displayName: Certificate Secret Reference
        path: service.certificateSecretRef
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Route
        path: route
      - description: An array consisting of service ports.
        displayName: Ports
        path: service.ports
      - description: Expose the application as a bindable service. Defaults to false.
        displayName: Bindable
        path: service.bindable
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Serviceability
        path: serviceability
      - displayName: Single sign-on
        path: sso
      - displayName: Monitoring
        path: monitoring
      - description: An array of environment variables for the application container.
        displayName: Environment Variables
        path: env
      - description: Specifies the strategy to replace old deployment pods with new pods.
        displayName: Deployment Update Strategy
        path: deployment.updateStrategy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:updateStrategy
      - description: List of sources to populate environment variables in the application container.
        displayName: Environment Variables from Sources
        path: envFrom
      - description: Represents a volume with data that is accessible to the application container.
        displayName: Volumes
        path: volumes
      - description: Specifies the strategy to replace old StatefulSet pods with new pods.
        displayName: StatefulSet Update Strategy
        path: statefulSet.updateStrategy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Represents where to mount the volumes into the application container.
        displayName: Volume Mounts
        path: volumeMounts
      - description: List of containers to run before other containers in a pod.
        displayName: Init Containers
        path: initContainers
      - displayName: Storage
        path: statefulSet.storage
      - description: List of sidecar containers. These are additional containers to be added to the pods.
        displayName: Sidecar Containers
        path: sidecarContainers
      - description: A convenient field to set the size of the persisted storage.
        displayName: Storage Size
        path: statefulSet.storage.size
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Affinity
        path: affinity
      - description: The directory inside the container where this persisted storage will be bound to.
        displayName: Storage Mount Path
        path: statefulSet.storage.mountPath
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Security context for the application container.
        displayName: Security Context
        path: securityContext
      - description: A YAML object that represents a volumeClaimTemplate component of a StatefulSet.
        displayName: Storage Volume Claim Template
        path: statefulSet.storage.volumeClaimTemplate
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:PersistentVolumeClaim
      - description: Labels to set on ServiceMonitor.
        displayName: Monitoring Labels
        path: monitoring.labels
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: A YAML snippet representing an array of Endpoint component from ServiceMonitor.
        displayName: Monitoring Endpoints
        path: monitoring.endpoints
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:endpointList
      - description: Controls which nodes the pod are scheduled to run on, based on labels on the node.
        displayName: Node Affinity
        path: affinity.nodeAffinity
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:nodeAffinity
      - description: Controls the nodes the pod are scheduled to run on, based on labels on the pods that are already running on the node.
        displayName: Pod Affinity
        path: affinity.podAffinity
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podAffinity
      - description: Enables the ability to prevent running a pod on the same node as another pod.
        displayName: Pod Anti Affinity
        path: affinity.podAntiAffinity
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podAntiAffinity
      - description: A YAML object that contains a set of required labels and their values.
        displayName: Node Affinity Labels
        path: affinity.nodeAffinityLabels
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Annotations to be added to the Route.
        displayName: Route Annotations
        path: route.annotations
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Hostname to be used for the Route.
        displayName: Route Host
        path: route.host
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Path to be used for Route.
        displayName: Route Path
        path: route.path
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'A name of a secret that already contains TLS key, certificate and CA to be used in the route. It can also contain destination CA certificate. The following keys are valid in the secret: ca.crt, destCA.crt, tls.crt, and tls.key.'
        displayName: Certificate Secret Reference
        path: route.certificateSecretRef
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: TLS termination policy. Can be one of edge, reencrypt and passthrough.
        displayName: Termination
        path: route.termination
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: HTTP traffic policy with TLS enabled. Can be one of Allow, Redirect and None.
        displayName: Insecure Edge Termination Policy
        path: route.insecureEdgeTerminationPolicy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Periodic probe of container liveness. Container will be restarted if the probe fails.
        displayName: Liveness Probe
        path: probes.liveness
      - description: Periodic probe of container service readiness. Container will be removed from service endpoints if the probe fails.
        displayName: Readiness Probe
        path: probes.readiness
      - description: Probe to determine successful initialization. If specified, other probes are not executed until this completes successfully.
        displayName: Startup Probe
        path: probes.startup
      statusDescriptors:
      - displayName: Service Binding
        path: binding
      - displayName: Status Conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      version: v1
    - description: Day-2 operation for generating server dumps
      displayName: WebSphereLibertyDump
      kind: WebSphereLibertyDump
      name: webspherelibertydumps.liberty.websphere.ibm.com
      statusDescriptors:
      - description: Location of the generated dump file
        displayName: Dump File Path
        path: dumpFile
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      version: v1
    - description: Day-2 operation for gathering server traces
      displayName: WebSphereLibertyTrace
      kind: WebSphereLibertyTrace
      name: webspherelibertytraces.liberty.websphere.ibm.com
      version: v1
  displayName: WebSphere Liberty
  icon:
  - base64data: PHN2ZyBpZD0iV2Vic3BoZXJlTGliZXJ0eSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB2aWV3Qm94PSIwIDAgMzIgMzIiPjxkZWZzPjxsaW5lYXJHcmFkaWVudCBpZD0ia2MxZXdoeGhoYSIgeDE9IjE2IiB5MT0iMjkiIHgyPSIxNiIgeTI9IjMiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBvZmZzZXQ9IjAiIHN0b3AtY29sb3I9IiNmZmYiIHN0b3Atb3BhY2l0eT0iMCIvPjxzdG9wIG9mZnNldD0iLjI2IiBzdG9wLWNvbG9yPSIjZmZmIi8+PC9saW5lYXJHcmFkaWVudD48bGluZWFyR3JhZGllbnQgaWQ9InNsMGYxYWJudGIiIHgxPSIyIiB5MT0iMjIuNSIgeDI9IjMwIiB5Mj0iMjIuNSIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPjxzdG9wIG9mZnNldD0iLjM1IiBzdG9wLWNvbG9yPSIjZmZmIi8+PHN0b3Agb2Zmc2V0PSIuNyIvPjwvbGluZWFyR3JhZGllbnQ+PGxpbmVhckdyYWRpZW50IGlkPSJhd3JyY2JjcXJjIiB4MT0iMi40NSIgeTE9IjEyLjgzOSIgeDI9IjE2IiB5Mj0iMTIuODM5IiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PHN0b3Agb2Zmc2V0PSIwIiBzdG9wLWNvbG9yPSIjZmZmIiBzdG9wLW9wYWNpdHk9IjAiLz48c3RvcCBvZmZzZXQ9Ii44IiBzdG9wLWNvbG9yPSIjZmZmIi8+PC9saW5lYXJHcmFkaWVudD48bGluZWFyR3JhZGllbnQgaWQ9IndvcGp4c3V4NGUiIHkxPSIzMiIgeDI9IjMyIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PHN0b3Agb2Zmc2V0PSIuMSIgc3RvcC1jb2xvcj0iI2E1NmVmZiIvPjxzdG9wIG9mZnNldD0iLjkiIHN0b3AtY29sb3I9IiMwZjYyZmUiLz48L2xpbmVhckdyYWRpZW50PjxtYXNrIGlkPSI2a3kxMnd4eDlkIiB4PSIwIiB5PSIwIiB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIG1hc2tVbml0cz0idXNlclNwYWNlT25Vc2UiPjxwYXRoIHN0eWxlPSJmaWxsOnVybCgja2MxZXdoeGhoYSkiIGQ9Ik0xNSAzaDJ2MjZoLTJ6Ii8+PHBhdGggZD0iTTE2IDMwQTE0LjAxNSAxNC4wMTUgMCAwIDEgMiAxNmwxLTEgMSAxYTEyIDEyIDAgMCAwIDI0IDBoMmExNC4wMTUgMTQuMDE1IDAgMCAxLTE0IDE0eiIgc3R5bGU9ImZpbGw6dXJsKCNzbDBmMWFibnRiKSIvPjxwYXRoIGQ9Ik0xNiAyMmEyMi43NCAyMi43NCAwIDAgMS0xMy41NS00LjA4OGwxLjIxMi0xLjU5MUEyMC43MTYgMjAuNzE2IDAgMCAwIDE2IDIweiIgc3R5bGU9ImZpbGw6I2ZmZiIvPjxwYXRoIGQ9Ik0zLjY2MiAxNS42NzkgMi40NSAxNC4wODhBMjIuNzM2IDIyLjczNiAwIDAgMSAxNiAxMHYyYTIwLjcxNiAyMC43MTYgMCAwIDAtMTIuMzM4IDMuNjc5eiIgc3R5bGU9ImZpbGw6dXJsKCNhd3JyY2JjcXJjKSIvPjxwYXRoIGQ9Ik00IDE2SDJBMTQuMDA2IDE0LjAwNiAwIDAgMSAyMS44NTUgMy4yOEwyMS4wMiA1LjFBMTIuMDA4IDEyLjAwOCAwIDAgMCA0IDE2eiIgc3R5bGU9ImZpbGw6I2ZmZiIvPjwvbWFzaz48L2RlZnM+PGcgc3R5bGU9Im1hc2s6dXJsKCM2a3kxMnd4eDlkKSI+PHBhdGggc3R5bGU9ImZpbGw6dXJsKCN3b3BqeHN1eDRlKSIgZD0iTTAgMGgzMnYzMkgweiIvPjwvZz48cGF0aCBkPSJNMjcgMTRhMy42MTUgMy42MTUgMCAwIDEgLjgzMi0xLjk0NUE1LjMzNCA1LjMzNCAwIDAgMCAyOSA5aC0yYTMuNjE1IDMuNjE1IDAgMCAxLS44MzIgMS45NDVBNS4zMzQgNS4zMzQgMCAwIDAgMjUgMTR6IiBzdHlsZT0iZmlsbDojMDAxZDZjIi8+PHBhdGggZD0iTTI1IDE5YTUuMDA2IDUuMDA2IDAgMCAwIDUtNWgtMmEzIDMgMCAwIDEtNiAwYzAtMS40ODguOC0yLjUyIDEuNzM2LTMuNzE2QTguMjMxIDguMjMxIDAgMCAwIDI2IDVWNGgtMnYxYzAgMS42OTEtLjg1NCAyLjc4Ny0xLjg0MiA0LjA1NUE3LjgxMSA3LjgxMSAwIDAgMCAyMCAxNGE1LjAwNiA1LjAwNiAwIDAgMCA1IDV6TTI4LjUgMjAuMDY0YTcuMTI2IDcuMTI2IDAgMCAxLTcgMGwtMSAxLjczMWE4Ljk0MyA4Ljk0MyAwIDAgMCAzLjUgMS4xMzlWMjhoMnYtNS4wNjZhOC45NDMgOC45NDMgMCAwIDAgMy41LTEuMTM0eiIgc3R5bGU9ImZpbGw6IzAwMWQ2YyIvPjwvc3ZnPg==
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - WebSphere Liberty
  - MicroProfile
  - Jakarta EE
  - Java
  - Application Server
  - Application Runtime
  - Runtime
  - Spring
  - Application
  - Open Source
  - WebSphereLiberty
  - WLO
  links:
  - name: Documentation
    url: https://github.com/WASdev/websphere-liberty-operator/tree/master/doc
  - name: WebSphere Liberty
    url: https://openliberty.io/
  - name: WebSphere Liberty Images
    url: https://github.com/WASdev/ci.docker
  maintainers:
  - email: arturdzm@ibm.com
    name: Artur Dzmitryieu
  - email: leojc@ca.ibm.com
    name: Leo Christy Jesuraj
  maturity: beta
  provider:
    name: IBM
  version: 0.0.0
