apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: websphereliberty-app-sample
spec:
  license:
    accept: false
    edition: IBM WebSphere Application Server
    productEntitlementSource: Standalone
  applicationImage: icr.io/appcafe/open-liberty/samples/getting-started@sha256:323580e543429bd299f127c8956aaf319a670bce619510d3ebb67282afabb514
  expose: true
  manageTLS: true
  replicas: 1
  serviceAccount:
    mountToken: true

