apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


bases:
- ../../overlays/watch-another-namespace

patchesStrategicMerge:
- wlo-deployment.yaml
- wlo-roles.yaml
- wlo-sa.yaml
- watched-roles.yaml
