apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: websphere-liberty-leader-election-rolebinding
  namespace: wlo-ns
subjects:
- kind: ServiceAccount
  name: websphere-liberty-controller-manager
