apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wlo-ns2

bases:
- ../../../overlays/watch-another-namespace/wlo-ns

patchesStrategicMerge:
- wlo-deployment.yaml
- wlo-roles.yaml
- wlo-sa.yaml