# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/liberty.websphere.ibm.com_webspherelibertyapplications.yaml
- bases/liberty.websphere.ibm.com_webspherelibertydumps.yaml
- bases/liberty.websphere.ibm.com_webspherelibertyperformancedata.yaml
- bases/liberty.websphere.ibm.com_webspherelibertytraces.yaml

# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_webspherelibertyapplications.yaml
#- patches/webhook_in_webspherelibertydumps.yaml
#- patches/webhook_in_webspherelibertyperformancedata.yaml
#- patches/webhook_in_webspherelibertytraces.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

- path: patches/preserveUnknownFields_webspherelibertyapplications.yaml
- path: patches/preserveUnknownFields_webspherelibertydumps.yaml
- path: patches/preserveUnknownFields_webspherelibertyperformancedata.yaml
- path: patches/preserveUnknownFields_webspherelibertytraces.yaml
# +kubebuilder:scaffold:preserveunknownfieldspatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
