apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: ibm-websphere-liberty.v0.0.0
  namespace: placeholder
  annotations:
    containerImage: icr.io/cpopen/websphere-liberty-operator:daily
    createdAt: 2025-08-19T12:14:58Z