apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../rbac

# Adds namespace to all resources.
namespace: default
namePrefix: websphere-liberty-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/instance: websphere-liberty-operator
  app.kubernetes.io/name: websphere-liberty-operator

