apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wlo-ns


resources:
- ../../overlays/watch-all-namespaces
patches:
- path: wlo-leader-election-cluster-rolebinding.yaml
- path: wlo-manager-cluster-rolebinding.yaml
