apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wlo-watched-ns2


resources:
- ../../../overlays/watch-another-namespace/wlo-watched-ns
patches:
- path: role-patch1.yaml
- path: role-patch2.yaml
- path: role-patch3.yaml
- path: role-patch4.yaml
