apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../manager

# Adds namespace to all resources.
namespace: websphere-liberty
namePrefix: websphere-liberty-

# Labels to add to all resources and selectors.
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: websphere-liberty-operator
    app.kubernetes.io/name: websphere-liberty-operator
    control-plane: websphere-liberty-controller-manager

patches:
- path: patches/delete-namespace.yaml
- path: patches/watch-namespace.yaml
